# Label PRs that touch Go backend code
backend:
  - changed-files:
    - any-glob-to-any-file:
      - 'cmd/**/*'       # CLI / entrypoint code
      - 'pkg/**/*'       # Shared packages
      - 'go.mod'         # Go module definition
      - 'go.sum'         # Go module checksums

# Label PRs that touch database migrations
database:
  - changed-files:
    - any-glob-to-any-file:
      - 'migrations/**/*'

# Label PRs that touch the frontend
frontend:
  - changed-files:
    - any-glob-to-any-file:
      - 'web/**/*'

# Label PRs that update documentation
documentation:
  - changed-files:
    - any-glob-to-any-file:
      - 'README.md'