# .github/labeler.yml
# NOTE: Indentation is critical here — each level must be exactly 2 spaces

backend:
  - 'cmd/**/*'
  - 'pkg/**/*'
  - 'go.mod'
  - 'go.sum'

database:
  - 'migrations/**/*'

frontend:
  - 'web/**/*'

documentation:
  - 'README.md'