backend:
  - changed-files:
      - any-glob-to-any-file:
          - 'cmd/**/*'
          - 'pkg/**/*'
          - 'go.mod'
          - 'go.sum'

database:
  - changed-files:
      - any-glob-to-any-file:
          - 'migrations/**/*'

frontend:
  - changed-files:
      - any-glob-to-any-file:
          - 'web/**/*'

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - 'README.md'